eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: false # 此应用为注册中心，false：不向注册中心注册自己。
    fetch-registry: false   # 注册中心职责是维护服务实例，false：不检索服务。
  server:
    enable-self-preservation: false
spring:
  application:
    name: EUREKA
server:
  port: 8761